### ISSUE TITLE
Three-document format or one-document?

### ISSUE THREAD

**Issue by littledan** [tc39/code-of-conduct#13]
When I shared around the JSFoundation code of conduct before the January meeting, a few people responded with the general message, "where's the specificity around reporting and enforcement"? It's there, just in two separate, linked documents. This code of conduct preserves the factoring. I see a big benefit in terms of, most of the time, people should just think about the recommendations for their own conduct. However, is this format sufficient for the committee to do reviews? Should it be in a single document for ease of skimming, as most other CoCs are?

**Comment by leobalter** [comment]
Browsing the parts of this CoC with multiple docs is comfortable and easy for me. That's my personal opinion and for sure it's not valid to everyone and neither represents a majority. 

I'm neutral to any format if we decide on one based on how it is easy to be consumed.

**Comment by leobalter** [comment]
Do we have more feedback on this? 

I worked on several feedbacks and the current format was ok.

**Comment by littledan** [comment]
OK, seems fine to me, unless the people who mentioned this before want to raise this concern further. I just wanted to make sure the point wasn't lost.

**Comment by leobalter** [comment]
My personal, subjective opinion so far: for the website, it's easier to read it with different pages. As the Ecma document, the same page is enough. I'll probably merge the Index with the Enforcement and Reporting files and experiment. It should be easier to release is an Ecma's document.
