### ISSUE TITLE
Should we offer a means of anonymous reporting?

### ISSUE THREAD

**Issue by ajklein** [tc39/code-of-conduct#16]
The [Chromium code of conduct](https://www.chromium.org/conduct) does this, for example. They do note that it may be harder to take action on an anonymous report.

But it still seems like it could be valuable to encourage people to speak up even if they don't feel comfortable bringing something to the advisory committee with their name attached.

**Comment by ljharb** [comment]
Yes. The goal should always be that everyone feels  comfortable reporting publicly. The only way to be sure that is true is if there is an equally accessible way to report anonymously and privately.

**Comment by gnarf** [comment]
:+1: to the general idea.  Chromium's uses a google form, is that something we could use?

**Comment by leobalter** [comment]
As soon as we have the subcommittee formed w/ the proper email we use, we can also define something to address this. I believe this should be the first group task for the CoC subcommittee.

**Comment by hackygolucky** [comment]
If anonymous reporting is allowed, there may need to be a disclaimer on the form that actions may be limited by not being able to do further reach out for the report and enforcement. I know y'all said that it's already been mentioned that it's difficult to execute on anonymous reports--and I've had to do it. It's very, very difficult.

**Comment by ctcpip** [comment]
committee discussed on `2023-06-22` - quorum (@ctcpip, @hemanth, @mpcsh) is in favor of this, probably via a Google Forms form (or equivalent), but first step is to draft the change to the CoC itself, and get that through committee (and Ecma?)

**Comment by ctcpip** [comment]
committee discussed `2023-08-31` and felt that the path forward here may be to recommend the person to create a throwaway/anonymous email account and use the existing reporting mechanism.  this allows them to remain anonymous and allows for follow-up communication.

**Comment by tabatkins** [comment]
Ping for PR review (no rush, of course).
