### ISSUE TITLE
Recommend secondary support to report to for rare-ish conflict of interest

### ISSUE THREAD

**Issue by hackygolucky** [tc39/code-of-conduct#20]
It is awesome that a sub-committee with explicitly listed members is being built for reporting violations. https://github.com/tc39/code-of-conduct-proposal/blob/master/Reporting.md It's a really good way to make folks feel safer to report. In the rare occasion that a person _on_  that list is the person to be reported, I'd recommend a secondary last-line-of defense(is there a lead officer or something?) person(s) able to handle this. Conflicts of interest in these cases are unfortunate, but I've personally seen them happen at events and in OSS.

**Comment by leobalter** [comment]
this makes sense. We'll need to discuss how this can be properly handled as the current alternative is a contact to the Ecma's ExeCom, which is usually formed by other members. This needs investigation if the alternative will be good enough to protect the defense line.

**Comment by ctcpip** [comment]
this should be addressed as people can choose to email any member of the committee
