### ISSUE TITLE
Brief Report from the Ecma April 26-27 ExeCom meeting on the TC39 Code-of-Conduct issue:

### ISSUE THREAD

**Issue by ecmageneva** [tc39/code-of-conduct#25]
[cc-2017-004-Rev1.pdf](https://github.com/tc39/code-of-conduct-proposal/files/975895/cc-2017-004-Rev1.pdf)
1) The idea was welcome by the ExeCom. We discussed if because of its importance it should be an Ecma-wide policy. The decision was that we first should keep it as an "experimental" policy within TC39, and may be later we could adopt it as an Ecma-wide policy. This is a typical practice what we do with new policy additions in Ecma.
2) So then the next exercise was how to incorporate the TC39 code-of-conduct into the Ecma "Bylaws" and "Rules" framework, where we have some measures if someone violating the policies. Also, we tried to come closer to the Ecma policy drafting style, which is on purpose very compact and avoids micro-management. You will see some effect on that in the new draft.
3) There are still some comments in the draft, which I think is useful because it gives some explanation of the points.
4) The attached document is very clearly also a draft, the final text has to be a document that de-facto both TC39 and the ExeCom agrees too. There are also some volunteers on the ExeCom side to continue to work on this with TC39 folks. So any comments on the draft is welcome.
5) By the way when I prepared the input document to the Execom as PDF I have copied what I found on the the GitHub as draft using and incorporating the different links of the GitHub documents. I hope I managed to capture the entire document correctly. Nevertheless should I have left out something please let me know asap.

**Comment by leobalter** [comment]
Thanks for the detailed feedback, @ecmageneva. I'm expecting a follow up during the meeting in the next week.

**Comment by leobalter** [comment]
The feedback from the Exec Committee is already discussed and addressed in the current version.
