### ISSUE TITLE
Add a CODE_OF_CONDUCT.md file to the main repos in the TC39 org

### ISSUE THREAD

**Issue by leobalter** [tc39/code-of-conduct#35]
We should add a CODE_OF_CONDUCT.md file pointing to this Code of Conduct document in each of the main repo of the TC39 org on GitHub.

- [X] ecma262
- [X] ecma402
- [X] Test262
- [X] Reflector
- [X] tc39-notes
- [X] proposals
- [X] agendas
- [ ] process-document
- [X] code-of-conduct (this one as well)

I'm certainly missing more repos here, please let me know and I'll add.

@maggiepint can you help me with this?

**Comment by michaelficarra** [comment]
Is a link not sufficient? Imagine the pain of updating all of those repos if we update the policy. And the problems/risks associated with forgetting to update one.

**Comment by leobalter** [comment]
my idea is only creating the file as GitHub handles it and the contents should just be a link to this repo/generated html pages.

**Comment by littledan** [comment]
Good idea, thanks for following up on this. Should each proposal repository have a similar .md file? It could go in https://github.com/tc39/template-for-proposals . cc @ljharb

**Comment by leobalter** [comment]
I believe so, as long as the file contains a quick link to this document. Otherwise, as pointed by @michaelficarra, it will become a nightmare to maintain more content from different repos.

**Comment by ljharb** [comment]
I think that whatever we decide should definitely go in the template.

However, I agree very strongly with https://github.com/tc39/code-of-conduct/issues/35#issuecomment-343245294 - we should have a file that merely links to the single source of truth for the CoC.

**Comment by jorydotcom** [comment]
In our CoC committee meeting today, we took a pass at this file (see [this gist](https://gist.github.com/jorydotcom/67b311c2ab467f7d8a37aeae385e3155)) - once it is approved by the rest of the committee we can add it to those repos!

**Comment by ljharb** [comment]
Can we create a bot that automatically makes a PR to any org repo that lacks a CODE_OF_CONDUCT.md file?

**Comment by leobalter** [comment]
> Can we create a bot that automatically makes a PR to any org repo that lacks a CODE_OF_CONDUCT.md file?

I'm fine with it, but I would have to learn how to do this.

**Comment by littledan** [comment]
I'd be fine with adding such a bot, though among TC39 bot priorities, I'd say the project to to up the IP management bot is more important. If anyone is interested in working on bots, I bet Thomas Wood could use a collaborator on that.

**Comment by jorydotcom** [comment]
PRs have been opened on ecma262, Reflector, proposals, agendas, and code-of-conduct. 
I'm awaiting permission to open PRs on ecma402, test262, and tc39-notes.
I'm unclear how to proceed on process-document since it's a GH page? cc @bterlson

**Comment by jorydotcom** [comment]
Update: PRs open for everything except the process document.
