### ISSUE TITLE
Should we do Nonviolent communication trainings?

### ISSUE THREAD

**Issue by codehag** [tc39/code-of-conduct#42]
There is a long standing issue of aggressive and veiled language. There are several tools that we can use to address this. One that I am familiar with is Nonviolent communication. The most effective way of getting this tool for dealing with contentious situations is to do a training but there is also a book. 

What do people think of having a NVC training like once a year at tc39?

info: https://en.wikipedia.org/wiki/Nonviolent_Communication

**Comment by ljharb** [comment]
Sounds like a great opportunity for all of us to improve.

**Comment by jorydotcom** [comment]
I would LOVE to do that training. I'm really familiar with NVC methods & think they can work wonders. Not sure if it's a good idea for me to give it, but I am willing & able if so.

**Comment by codehag** [comment]
@jorydotcom very interesting! Have you had the NVC trainer training? this might be an option.

My only concern would be that it might be difficult for committee members to disassociate you from your role in the committee -- this might be a reason to have a trainer from the outside. I don't know if this would be an issue but it comes to mind when I think about a committee member doing the training.

**Comment by jorydotcom** [comment]
That would be my concern as well, I think it would be a better offering to have someone from outside the TC community, and ideally someone with the certification (which I do not have) to do it. I don't know what that would look like cost wise but we could/should investigate

**Comment by codehag** [comment]
If we can find funding, I know of two trainers in Berlin that could do it.

**Comment by ctcpip** [comment]
closing in favor of tc39/Admin-and-Business/issues/130 and tc39/inclusion-group/issues/31
