### ISSUE TITLE
Should we move CoC to tc39.github.io repository?

### ISSUE THREAD

**Issue by chicoxyzzy** [tc39/code-of-conduct#46]
That'll possibly make it easier to keep all links in sync and to add translations same way as they work for the website (I have ongoing work on [Russian translation](https://github.com/chicoxyzzy/code-of-conduct/pull/1)).

**Comment by ljharb** [comment]
I think it’s important to keep it as its own repo; if we moved it anywhere it’d be to the .github repo so it showed up across the org.

A GitHub org’s website contains the websites of every repo in the org; it’s not really practical to move everything on it into a single repo.
