### ISSUE TITLE
How to address situations while they are happening?

### ISSUE THREAD

**Issue by xjamundx** [tc39/code-of-conduct#5]
What's the proper way to say "Hey, you're not being nice or professional. Please stop". If someone struggles to comply what is the consequence? How many warnings? And who makes the final decision.

Probably this is overkill, but worth bringing it up. It seemed the main "reporting" suggestion was via email, but may be nice to have something that explains how to handle inappropriate conduct during meetings or related activities.

**Comment by littledan** [comment]
I think real-time feedback during meetings would need to be addressed by a chair group or meeting moderator. I'm not sure if a Code of Conduct can address it by itself, but maybe the CoC could give guidelines to moderators/chairs, and could be referenced by moderators/chairs as principles to strive for when intervening. In the January 2017 TC39 meeting, a group of people was set up to determine a governance structure for the committee, so could be a path to resolving that issue.

**Comment by leobalter** [comment]
> real-time feedback during meetings

Those are cases I expect the chair group to answer properly if any immediate action is necessary. 

> How many warnings?

This is something that needs proper evaluation on each case, IMHO. To avoid any weakness on not pre-establishing these procedures, we define a proper group to review issues, even during meetings.

> Probably this is overkill, but worth bringing it up.

It's nice to bring it up.

> It seemed the main "reporting" suggestion was via email, but may be nice to have something that explains how to handle inappropriate conduct during meetings or related activities.

the email is a kickstart, we can research and find alternatives. A clear info about the group to review issues is also good so they can be reached in person during meetings to at least figure out the next step.

**Comment by gnarf** [comment]
See also #15 -- The section in question is related.

**Comment by leobalter** [comment]
I'm updating the proposal with some rewordings that might bring some clarity for situations that includes a committee acting in an emergency. Let's see if it works

**Comment by ecmageneva** [comment]
In my opinion the Code of Conduct text is ok, but its implementation should be voluntary and no formal mechanism for enforcement should be created.

**Comment by ljharb** [comment]
@ecmageneva I'm not sure I understand; voluntary by who? The whole point of implementing a CoC is to enforce it.

**Comment by ecmageneva** [comment]
Voluntary by any TC39 meeting participant, TC39 member company.
WE can even dirstibute the Code of conduct text at the time when members join Tc39.

**Comment by ljharb** [comment]
Meaning a TC39 member can choose not to comply? I don't see why we would want that; violators shouldn't be permitted to participate/

**Comment by ecmageneva** [comment]
No, I TC39 member is expected to follow the code of conduct. By the way there is one paragraph in the Ecma bylaws (I think it is 5.2? but did not look it up right now...)  to expell an Ecma member, so the Ecma GA has the power to expell somebody it has to.

**Comment by ecmageneva** [comment]
It is Section 5 in the Ecma Bylaws:
Termination of Ecma membership
5.1
a) Membership of a company shall be terminated in the following cases:

Withdrawal by the company member:
Withdrawal by a company can only occur at the end of a calendar year and requires a written three-month notice carrying an authorized signature to the Secretary General (to be received by the Ecma Secretariat before 1 October).
The company ceasing to exist.

The conditions for membership set forth in Articles 3.2 and 3.3 of the present By-laws no longer being complied with.

By expulsion for violation of By-laws and Rules or for any other conduct prejudicial to the interest and correct functioning of the Association.

By expulsion after failure to pay the membership fee during the year in which it becomes due. This will happen automatically on 31 December and shall not relieve the member of the obligation to pay such fees that are due or past due according to the terms of the invoice. In justified hardship cases the Ecma management may extend - on a case by case basis - the membership payment deadline.
b) Membership of an NFP shall be terminated in the following cases:

At the end of the year, unless extension of NFP membership has been granted by the Ecma GA.
Withdrawal upon written notice to the Secretary General, to take effect upon receipt.
The NFP ceasing to exist.
By expulsion for violation of By-laws and Rules or for any other conduct prejudicial to the interest and correct functioning of the Association.
5.2
No company member may be expelled for failure to adhere to one or several agreed standards.

5.3
Any proposal to expel an Ecma member shall be backed by at least one-fifth of all the ordinary members. The proposal to expel shall be on the agenda for the General Assembly at which it is to be discussed so as to give the member the opportunity to present its case.

5.4
A two-thirds majority of all the ordinary members is necessary to expel an Ecma member. Such expulsion will become effective 15 days after notification by registered mail.

5.5
An Ecma member which has been expelled can only be re-admitted by the General Assembly with a two-thirds majority of all ordinary members.
